import { NextRequest, NextResponse } from 'next/server';
import connectDB from '@/lib/db';
import BotSettings from '@/lib/models/BotSettings';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

/**
 * GET /api/whatsapp-web/qr-code?botId=xxx
 * Get QR code for WhatsApp Web authentication from MongoDB
 * QR code is generated by worker service and stored in database
 */
export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const botId = searchParams.get('botId');

    if (!botId) {
      return NextResponse.json(
        { error: 'botId is required' },
        { status: 400 }
      );
    }

    await connectDB();
    
    // Đọc QR code từ MongoDB (được lưu bởi worker service)
    const botSettings = await BotSettings.findOne({ botId })
      .select('whatsapp.qrCode whatsapp.qrCodeExpiresAt whatsapp.enabled whatsapp.phoneNumber whatsapp.verifiedName')
      .lean() as any;

    if (!botSettings) {
      return NextResponse.json({ error: 'Bot not found' }, { status: 404 });
    }

    // Kiểm tra nếu đã authenticated (có phoneNumber nhưng không có QR code)
    if (botSettings.whatsapp?.phoneNumber && !botSettings.whatsapp?.qrCode) {
      return NextResponse.json({
        authenticated: true,
        phoneNumber: botSettings.whatsapp.phoneNumber,
        name: botSettings.whatsapp.verifiedName || botSettings.whatsapp.phoneNumber,
        message: 'WhatsApp Web is already authenticated'
      });
    }

    // Kiểm tra QR code có hợp lệ không
    if (botSettings.whatsapp?.qrCode && 
        botSettings.whatsapp?.qrCodeExpiresAt && 
        new Date(botSettings.whatsapp.qrCodeExpiresAt) > new Date()) {
      return NextResponse.json({
        qrCode: botSettings.whatsapp.qrCode,
        botId,
        message: 'Scan this QR code with WhatsApp to authenticate'
      });
    }

    // Nếu không có QR code hoặc đã hết hạn
    if (botSettings.whatsapp?.enabled) {
      return NextResponse.json({
        error: 'QR code not available yet. Worker service is generating QR code. Please wait a few seconds and try again.',
        message: 'Please ensure worker service is running on Railway/Render.'
      }, { status: 404 });
    }

    return NextResponse.json({
      error: 'WhatsApp Web bot is not enabled. Please enable it first.'
    }, { status: 400 });
  } catch (error: any) {
    console.error('❌ Error getting QR code:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to get QR code' },
      { status: 500 }
    );
  }
}

